name: Remove file from branches
on: workflow_dispatch  # 手动触发

jobs:
  remove-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有分支历史

      - name: Remove file from all branches
        run: |
          # 设置Git用户信息
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          file="generate_steam_lua.py"  # 替换为你的文件
          protected_branches="main|data"

          # 获取所有远程分支（排除受保护分支）
          branches=$(git branch -r | grep -v "HEAD" | sed 's/origin\///' | grep -v -E "$protected_branches")

          for branch in $branches; do
            git checkout "$branch"
            if [ -f "$file_to_delete" ]; then
              echo "删除文件 @ $branch"
              git rm "$file"
              git commit -m "Remove $file"
              git push origin "$branch"
            fi
          done
