name: Remove file from all branches

on:
  workflow_dispatch:  # 手动触发

jobs:
  remove-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Remove file from branches
        run: |
          pip install PyGithub
          python - <<EOF
          from github import Github
          import os

          g = Github(os.getenv('TOKEN'))
          repo = g.get_repo("${{ github.repository }}")
          file_path = "generate_steam_lua.py"  # 替换为你的文件路径
          protected_branches = ["main", "data"]

          for branch in repo.get_branches():
              if branch.name not in protected_branches:
                  try:
                      contents = repo.get_contents(file_path, ref=branch.name)
                      repo.delete_file(
                          path=file_path,
                          message=f"Remove {file_path} from {branch.name}",
                          sha=contents.sha,
                          branch=branch.name
                      )
                      print(f"Deleted from {branch.name}")
                  except Exception as e:
                      print(f"Error in {branch.name}: {e}")
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
